In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_preprocessed=pd.read_csv(r'C:\Users\Admin\Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

# Create the Target Variable

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
Target=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
Target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Ex. Absenteeism']=Target

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Ex. Absenteeism  
0                1  
1                0  
2                0  
3                1  
4                0

# Comment on Target

In [9]:
Target.sum()/Target.shape[0]

0.45571428571428574

In [10]:
data_with_target=data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [11]:
data_with_target is data_preprocessed

False

In [12]:
data_with_target.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Ex. Absenteeism  
0               30          0         2     1                1  
1               31          0         1     0                0  
2               31          0         0     0                0  
3               24          0         2     0                1  
4               30          0         2     1                0

# Selecting the input for Regression

In [13]:
data_with_target.shape

(700, 15)

In [14]:
data_with_target.iloc[:,0:14].head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

In [15]:
data_with_target.iloc[:,:-1].head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

In [16]:
unscaled_inputs=data_with_target.iloc[:,:-1]

# Standardize the Data

In [17]:
from sklearn.preprocessing import StandardScaler
Scaler=StandardScaler()

In [18]:
Scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [19]:
scaled_input=Scaler.transform(unscaled_inputs)

In [20]:
scaled_input[1:3]

array([[-0.57735027, -0.09298136, -0.31448545, -1.23944822,  0.03079619,
        -0.80094984, -1.57468098, -1.1418824 ,  2.13080317, -0.80633129,
         1.00263338, -0.44798003, -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545,  0.80681063,  0.03079619,
        -0.23290031, -0.6541427 ,  1.42674947,  0.24830984, -0.80633129,
         1.00263338, -0.44798003, -0.91902997, -0.58968976]])

In [21]:
scaled_input.shape

(700, 14)

In [22]:
from sklearn.model_selection import train_test_split


In [23]:
train_test_split(scaled_input,Target)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  2.8430157 ],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [24]:
X=scaled_input
y=Target

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=20)

In [26]:
print(X_train.shape,y_train.shape)

(560, 14) (560,)


In [27]:
print(X_test.shape,y_test.shape)

(140, 14) (140,)


In [28]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
model.score(X_train,y_train)

0.7839285714285714

# Manually check the Accaurcy

In [30]:
model_output=model.predict(X_train)
model_output

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [31]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [32]:
np.sum(model_output==y_train)  # total no. of true output

439

In [33]:
model_output.shape[0]  # total no. of observation

560

In [34]:
np.sum(model_output==y_train)/model_output.shape[0]  # Accuraccy

0.7839285714285714

# Finding the Coeff. and intercept

In [35]:
model.intercept_

array([-0.19634256])

In [36]:
model.coef_

array([[ 1.9295319 ,  0.30331301,  1.4183381 ,  1.13860328,  0.02152268,
        -0.08218596,  0.715129  , -0.06308903, -0.20725848, -0.02793688,
         0.32588045, -0.17669466,  0.37594127, -0.30651279]])

In [37]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [38]:
feature_name=unscaled_inputs.columns.values

In [42]:
Summary_Table=pd.DataFrame(columns=['Feature Name'], data = feature_name)
Summary_Table['Coefficient']=np.transpose(model.coef_)
Summary_Table

Feature Name  Coefficient
0                  Reason_1     1.929532
1                  Reason_2     0.303313
2                  Reason_3     1.418338
3                  Reason_4     1.138603
4               Month Value     0.021523
5               Day of Week    -0.082186
6    Transportation Expense     0.715129
7          Distance to Work    -0.063089
8                       Age    -0.207258
9   Daily Work Load Average    -0.027937
10          Body Mass Index     0.325880
11                Education    -0.176695
12                 Children     0.375941
13                     Pets    -0.306513

In [49]:
Summary_Table.index=Summary_Table.index + 1
Summary_Table.loc[0]=['Intercept', model.intercept_[0]]
Summary_Table=Summary_Table.sort_index()
Summary_Table

Feature Name  Coefficient
0                 Intercept    -0.196343
1                 Intercept    -0.196343
2                 Intercept    -0.196343
3                  Reason_1     1.929532
4                  Reason_2     0.303313
5                  Reason_3     1.418338
6                  Reason_4     1.138603
7               Month Value     0.021523
8               Day of Week    -0.082186
9    Transportation Expense     0.715129
10         Distance to Work    -0.063089
11                      Age    -0.207258
12  Daily Work Load Average    -0.027937
13          Body Mass Index     0.325880
14                Education    -0.176695
15                 Children     0.375941
16                     Pets    -0.306513

# Interpreting the coefficients

In [50]:
Summary_Table['Odds Ratio']=np.exp(Summary_Table.Coefficient)
Summary_Table

Feature Name  Coefficient  Odds Ratio
0                 Intercept    -0.196343    0.821731
1                 Intercept    -0.196343    0.821731
2                 Intercept    -0.196343    0.821731
3                  Reason_1     1.929532    6.886286
4                  Reason_2     0.303313    1.354338
5                  Reason_3     1.418338    4.130251
6                  Reason_4     1.138603    3.122404
7               Month Value     0.021523    1.021756
8               Day of Week    -0.082186    0.921101
9    Transportation Expense     0.715129    2.044450
10         Distance to Work    -0.063089    0.938860
11                      Age    -0.207258    0.812810
12  Daily Work Load Average    -0.027937    0.972450
13          Body Mass Index     0.325880    1.385250
14                Education    -0.176695    0.838036
15                 Children     0.375941    1.456362
16                     Pets    -0.306513    0.736009

In [54]:
Summary_Table.sort_values('Odds Ratio',ascending=False)

Feature Name  Coefficient  Odds Ratio
3                  Reason_1     1.929532    6.886286
5                  Reason_3     1.418338    4.130251
6                  Reason_4     1.138603    3.122404
9    Transportation Expense     0.715129    2.044450
15                 Children     0.375941    1.456362
13          Body Mass Index     0.325880    1.385250
4                  Reason_2     0.303313    1.354338
7               Month Value     0.021523    1.021756
12  Daily Work Load Average    -0.027937    0.972450
10         Distance to Work    -0.063089    0.938860
8               Day of Week    -0.082186    0.921101
14                Education    -0.176695    0.838036
0                 Intercept    -0.196343    0.821731
1                 Intercept    -0.196343    0.821731
2                 Intercept    -0.196343    0.821731
11                      Age    -0.207258    0.812810
16                     Pets    -0.306513    0.736009

# Project 1 Un Scaled Dummy Variable Absenteeism ML 3-5


In [1]:
#Too see the difference in the accuracy and selcected scaling